library(ggplot2)
library(ggthemes)
library(extrafont)
library(plyr)
library(scales)

##################
### HOW TO USE ###
##################

# Set WD to folder containing csv files. 
# These files can be generated by dumping the db into csv.


### General statements

# Import csv files
items <- read.csv("items.csv")
feedbacks <- read.csv("feedbacks.csv")

# Set constants

# All
marketplaces <- c("Alphabay", "Silk Road 1", "Evolution", "Black Market Reloaded", "Agora", "Pandora", "Hydra", "Silk Road 2")
# Without Evolution and Alphabay
marketplaces1 <- c("Silk Road 1", "Black Market Reloaded", "Agora", "Pandora", "Hydra", "Silk Road 2")
# Only Alphabay and Evolution
marketplaces2 <- c("Alphabay", "Evolution")
# All
categories <- c("malware", "app", "website", "hosting", "exploits", "botnet", "e-mail", "phone", "RAT", "other - account", "cash-out", "other - custom", "other - fake", "other - guide", "other - pirated software", "other - voucher/invite/codes/lottery/gift", "other")
# Without other
categories1 <-c("malware", "app", "website", "hosting", "exploits", "botnet", "e-mail", "phone", "RAT", "cash-out")
# Without "cash-out" & other
categories2 <-c("malware", "app", "website", "hosting", "exploits", "botnet", "e-mail", "phone", "RAT")
# Only other
categories3 <- c("other - account", "other - custom", "other - fake", "other - guide", "other - pirated software", "other - voucher/invite/codes/lottery/gift", "other")
### Graph for Average turnover / marketplace / day

# colors
cols <- c("red", "green", "yellow", "blue", "orange", "purple", "cyan", "magenta", "darkolivegreen1", "pink", "aquamarine4", "lavender", "brown", "beige", "maroon", "aquamarine", "darkolivegreen", "burlywood1", "navy", "grey", "black")


############################################
### Graph for total revenue per category ###
############################################

# Output data frame
out <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("marketplace", "category", "amount", "normalized")
colnames(out) <- x

# Iterate over all MPs
for (mp in marketplaces) {
  
    # Find all orders from mp
    orders <- subset(feedbacks, marketplace == mp)
    
    # Calc turnover
    total_revenue = sum(orders$order_amount_usd, na.rm = TRUE)
    
    # Iterate over all categories
    for (ct in categories) {
      
      # Find all orders from a category
      tmp <- subset(orders, category == ct)
      
      # Calcualte turnover
      revenue_ct = sum(tmp$order_amount, na.rm = TRUE)
      
      # round up
      normalized_revenue_ct = round( ((revenue_ct / total_revenue)*100), digits=2)
      
      # Store
      value = c(mp, ct, revenue_ct, normalized_revenue_ct)
      if (normalized_revenue_ct != 0){
        out[nrow(out)+1, ] <- value
      }
    }
}

# Plot
ggplot(out, aes(x = marketplace, y = as.numeric(amount), fill = category, linetype = category)) + 
  geom_bar(data=out, position = "fill", stat = "identity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle=0), legend.key.size = unit(0.5, "cm"), plot.title = element_text(hjust = 0.5)) +
  xlab("Marketplace") + 
  ylab("Percentage") +
  scale_fill_manual(values=cols) +
  ggtitle("Percentage of Turnover per Category per Marketplace")

######################################################
### Graph for total revenue per category per month ###
######################################################

out <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("date", "category", "order_amount")
colnames(out) <- x

# Iterate over categories
for (ct in categories3) {
  if (ct != "") {
    
    # Find orders
    orders <- subset(feedbacks, category == ct)
    
    # Format to year month
    orders$date <- format(as.Date(orders$date), "%Y-%m")
    
    dates <- orders$date
    
    # Find unique dates
    unique_dates <- unique(orders$date)
    turnover <- orders$order_amount_usd
    
    # Store in df
    df <- data.frame(date = dates, category=orders$category, order_amount = turnover)
    
    # Iterate over dates
    for (dt in unique_dates) {
      
      # Find entries with specific date
      tmp <- subset(df, date == dt)
      
      # Length
      length_tmp <- nrow(tmp)
      
      # Sum
      tmp <- ddply(tmp,"date", numcolwise(sum))
      tmp$category <- ct
      
      # Store on approx. middle of month.
      tmp$date <- paste(dt, "15", sep="-")
      
      # Make number smaller
      tmp$order_amount <- tmp$order_amount / 1000
      
      # Store
      out <- rbind(out, tmp)
    }
  }
}

# Sort
out$date <- as.Date(out$date)
out <- out[order(out$date),]

# Plot
ggplot(data=out, aes(x=date, order_amount, group=category)) + geom_line(aes(color = category, linetype = category)) + 
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  labs(x = "Date (Month)", y = "Turnover (1000 USD)") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ggtitle("Total Turnover per Category per Month (Only Other)")


############################################
### Graph Total turnover per marketplace ###
############################################

# Set data frame for ouput
out <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("date", "marketplace", "order_amount")
colnames(out) <- x

# iterate over mps
for (mp in marketplaces) {
  if (mp != "") {
    print(mp)
    
    # Get all feedbacks for current mp
    orders <- subset(feedbacks, marketplace == mp)
    
    # Rip out days
    orders$date <- format(as.Date(orders$date), "%Y-%m")
    
    # Dates
    dates <- orders$date
    
    # Unique dates
    unique_dates <- unique(orders$date)
    
    # Turnover
    turnover <- orders$order_amount_usd
    
    # DF with only categories, dates & amounts
    df <- data.frame(date = dates, category=orders$category, order_amount = turnover)
    
    #out <- data.frame(matrix(ncol = 3, nrow = 0))
    #x <- c("date", "marketplace", "order_amount")
    #colnames(out) <- x
    
    # Loop over all unique dates
    for (dt in unique_dates) {
      # Get all feedbacks with current date
      tmp <- subset(df, date == dt)
      
      # Amount of feedbacks
      length_tmp <- nrow(tmp)
      
      # Sum all amounts, leading to 1 entry
      tmp <- ddply(tmp,"date", numcolwise(sum))
      
      # Divide by 1000 readability
      tmp$order_amount <- tmp$order_amount / 1000
      
      # Store mp
      tmp$marketplace <- mp
      
      # Set to middle of month
      tmp$date <- paste(dt, "15", sep="-")
      
      # Store
      out <- rbind(out, tmp)
    }
  }
}

# Sort on date
out$date <- as.Date(out$date)
out <- out[order(out$date),]

# Plot
ggplot(data=out, aes(x=date, order_amount, group=marketplace)) + 
  geom_line(aes(color = marketplace, linetype = marketplace)) + 
  scale_x_date(date_breaks = "1 year", labels = date_format("%Y")) +
  labs(x = "Date (Month)", y = "Turnover (1000 USD)") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ggtitle("Total Turnover per Marketplace per Month")

#############################################################
### Percentage of Items per marketplace as fn of #vendors ###
#############################################################

# Output
out <- data.frame(matrix(ncol = 3, nrow = 0))
x <- c("vendor", "marketplace", "amount")
colnames(out) <- x

# Unique vendors
unique_vendors <- unique(items$vendor_hash) 
unique_vendors <- unique_vendors[unique_vendors != ""]

for (vr in unique_vendors) {
  if (vr != "") {
    # Find all entries with vr
    vr_listings <- subset(items, vendor_hash == vr)
    
    # Find all unique mps
    unique_mps <- unique(vr_listings$marketplace)
    
    # Iterate over mps
    for (mp in unique_mps) {
      if (mp != "") {
        # Calculate numbers of listings
        # Could be done out of loop for performance
        listings_mp <- subset(items, marketplace == mp & item_hash != "" & vendor_hash !="")
        no_listings_mp <- nrow(listings_mp)
        
        # Find all listings of MP from VR
        tmp <- subset(vr_listings, marketplace == mp)
        
        # Calculate percentage
        percentage_listings_vr <- nrow(tmp) / no_listings_mp
        
        # Store
        out[nrow(out)+1, ] <- c(vr, mp, percentage_listings_vr)
      }
    }
  }
}

# Order
out$amount <- as.numeric(out$amount)
out <- out[order(out$marketplace, -out$amount),]

# Output for plot
out2 <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("number", "vendor", "marketplace", "amount")
colnames(out2) <- x

# Iterate mps
for (mp in marketplaces2) {
  
  # Find entries for mp
  tmp <- subset(out, marketplace == mp)
  if (nrow(tmp) > 0 ) {
    # Fill with number of vendors
    tmp$number <- seq(1, nrow(tmp))
    
    # Sum with previous entries in order to gain cummulative function
    counter <- 2
    for (item in tmp$amount) {
      if (counter <= length(tmp$amount)) {
      tmp$amount[counter] <- as.numeric(tmp$amount[counter-1]) + as.numeric(tmp$amount[counter])
      counter <- counter + 1
      }
    }
    
    # Store output
    out2 <- rbind(out2, tmp) 
  }
}

# Plot
ggplot(data=out2, aes(number, amount, colour=marketplace)) + 
  geom_line() +
  labs(x = "Number of vendors", y = "Fraction of items in marketplace") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ggtitle("Proportion of Items in Marketplace as a Function of the Number of Vendors (Only Alphabay and Evolution)") + 
  scale_x_continuous(breaks = seq(0, 3200, 500))

#############################################
### Percentage of Items as fn of #vendors ###
#############################################

# Output
out3 <- data.frame(matrix(ncol = 2, nrow = 0))
x <- c("vendor", "amount")
colnames(out3) <- x

# Calc #listings
listings <- subset(items, marketplace != "" & item_hash != "" & vendor_hash !="")
no_listings <- nrow(listings)

# Unique vendors
unique_vendors <- unique(items$vendor_hash) 
unique_vendors <- unique_vendors[unique_vendors != ""]

# Iterate over vendors
for (vr in unique_vendors) {
  if (vr != "") {
    
    # Store percentage of listings
    vr_listings <- subset(items, vendor_hash == vr)
    out3[nrow(out3)+1, ] <- c(vr, nrow(vr_listings)/no_listings)
  }
}

# Order
out3$amount <- as.numeric(out3$amount)
out3 <- out3[order(-out3$amount),]

# Set number of vendors
out4 <- out3
out4$number <- seq(1, nrow(out3))

# Sum for cummulative distribution function
counter <- 2
for (item in out4$amount) {
  if (counter <= length(out4$amount)) {
    out4$amount[counter] <- as.numeric(out4$amount[counter-1]) + as.numeric(out4$amount[counter])
    counter <- counter + 1
  }
}

# Plot
ggplot(data=out4, aes(number, amount)) + 
  geom_line() + 
  labs(x = "Number of vendors", y = "Fraction of items") + 
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  ggtitle("Proportion of Items as a Function of the Number of Vendors") + 
  scale_x_continuous(breaks = seq(0, 6000, 500))
