library(ggplot2)
library(ggthemes)
library(extrafont)
library(plyr)
library(scales)


##################
### HOW TO USE ###
##################

# Set WD to folder containing csv files. 
# These files can be generated by dumping the db into csv.


### General statements

# Import csv files
items <- read.csv("items.csv")
feedbacks <- read.csv("feedbacks.csv")


# Dates
min_date = min(as.Date(items$first_observed), na.rm = TRUE)
max_date = max(as.Date(items$last_observed), na.rm = TRUE)

#print (min_date)
#print (max_date)

# Set data frame for ouput
out <- data.frame(matrix(ncol = 5, nrow = 0))
x <- c("date", "sellers", "marketplaces", "sales", "countries")
colnames(out) <- x

theDate <- min_date

library(lubridate)

# Unique dates
unique_dates <- unique(feedbacks$date)

for (dt in unique_dates) {
  tmp <- subset(feedbacks, date == dt & category != "other")

  u_sellers <- length(unique(tmp$receiver_hash))
  if (u_sellers == 0) {
    print ("brijke", dt)
    break
  }
  unique_hash <- unique(tmp$receiver_hash)
  u_mp <- length(unique(tmp$marketplace))
  sales <- sum(tmp$order_amount_usd)
  
  for (vhash in unique_hash) {
    tmp2 <- subset(items, vendor_hash == vhash)
    u_countries <- length(unique(tmp2$ships_from))
  }
  
  entry<-data.frame(dt, u_sellers, u_mp, sales, u_countries, nrow(tmp))
  colnames(entry)<-x
  
  out <- rbind(out, entry)
}

library("ggpubr")
ggscatter(out, x = "sellers", y = "marketplaces", 
          conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "kendall",
          xlab = "number of sellers", ylab = "marketplaces")

library("ggpubr")
 ggscatter(out, x = "sellers", y = "sales", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "kendall",
           xlab = "number of sellers", ylab = "sales")
 
library("ggpubr")
 ggscatter(out, x = "sellers", y = "countries", 
           add = "reg.line", conf.int = TRUE, 
           cor.coef = TRUE, cor.method = "kendall",
           xlab = "number of sellers", ylab = "countries")

res <- cor.test(out$sellers, out$marketplaces, 
                method = "kendall")
res

res <- cor.test(out$sellers, out$sales, 
                method = "kendall")
res

res <- cor.test(out$sellers, out$countries, 
                method = "kendall")
res

