library(ggplot2)
library(ggthemes)
library(extrafont)
library(plyr)
library(scales)
library("ggpubr")
library("dplyr")   


##################
### HOW TO USE ###
##################

# Set WD to folder containing csv files. 
# These files can be generated by dumping the db into csv.


### General statements

# Import csv files
items <- read.csv("items.csv")
feedbacks <- read.csv("feedbacks.csv")

# All
marketplaces <- c("Alphabay", "Silk Road 1", "Evolution", "Black Market Reloaded", "Agora", "Pandora", "Hydra", "Silk Road 2")

# Dates
min_date = min(as.Date(items$first_observed), na.rm = TRUE)
max_date = max(as.Date(items$last_observed), na.rm = TRUE)

#print (min_date)
#print (max_date)

# Set data frame for ouput
out <- data.frame(matrix(ncol = 6, nrow = 0))
x <- c("date", "sellers", "marketplaces", "sales", "countries", "country_list")
colnames(out) <- x
out0 <- data.frame(matrix(ncol = 5, nrow = 0))
x0 <- c ("date", "seller", "sales", "percentage", "revenue")
colnames(out0) <- x0

theDate <- min_date

library(lubridate)

# Unique dates
unique_dates <- unique(feedbacks$date)
 for (dt in unique_dates) {
   tmp0 <- subset(feedbacks, date == dt & category != "other")
   trev <- sum(tmp0$order_amount_usd)
   
   #For each unique seller, get total sales and percentage of total revenue per day
   
   for (us in unique(tmp0$receiver_hash)) {
    
     #tmp01 <- subset(feedbacks, receiver_hash == us & date == dt & category != "other")
     tmp01 <- subset(tmp0, receiver_hash == us)
     tsales <- sum(tmp01$order_amount_usd)
     tp <- (tsales / trev) * 100
     
     entry0 <- data.frame(dt, us, tsales, tp, trev, nrow(tmp01))
     colnames(entry0) <- x0
     out0 <- rbind(out0, entry0)
     
     
   }
   
   #Order in decreasing order of percentage
   
   out0 <- out0[order(-out0$percentage), ]
     sum <- 0
     for(row in 1: nrow(out0)) {
       sum <- sum + out0[row, "percentage"]
       if (sum >= 20) {
         out0 <- out0[ 1:row, ]
         break
       }
     }
     
   for (us in unique(out0$seller)) {
     tmp <- subset(tmp0, receiver_hash == us)
     u_sellers <- length(out0$seller)
  
     u_mp <- length(tmp$marketplace)
      if (u_mp == 0) {
        u_mp = 2
    }
  sales <- sum(tmp$order_amount_usd)
  
    tmp2 <- subset(items, vendor_hash == us)
    country_list <- unique(tmp2$ships_from)
    u_countries <- length(unique(tmp2$ships_from))
  
  entry<-data.frame(dt, u_sellers, u_mp, sales, u_countries, country_list, nrow(tmp))
  colnames(entry)<-x
  
  out <- rbind(out, entry)
   }
 }

out$date <- as.Date(out$date)
out <- out[order(out$date),]

head(out)

out$d <- as.Date(out$date)
out$Month <- months(out$d)
out$Year <- format(out$d, format="%y")

out$Month <- as.Date.character(cut(out$date, breaks = "month")) 
#out2$date <- as.Date.character(cut(out$date, breaks = "month")) 


avg_sellers <- aggregate(sellers ~ Month + Year, out, mean)
avg_markets <- aggregate(marketplaces ~ Month + Year, out, mean)
avg_sales <- aggregate(sales ~ Month + Year, out, mean)
avg_countries <- aggregate(countries ~ Month + Year, out, mean)

out2 <- data.frame(matrix(ncol = 6, nrow = 0))
#entry2 <- data.frame(out$Month, "avg_sellers","avg_marketplaces","avg_sales","avg_countries")
entry2 <- data.frame(avg_sellers$Month, avg_sellers$sellers,avg_markets$marketplaces,avg_sales$sales,avg_countries$countries)
x2 <- c("month", "seller_range", "avg_sellers", "avg_marketplaces", "avg_sales", "avg_countries")
colnames(out2) <- x2
out2 <- rbind(out2, entry2)
model <- lm(avg_sellers$sellers ~ avg_markets$marketplaces + avg_sales$sales + avg_countries$countries, out2)


tempp1 <- data.frame(out)
#aggregate(~range(), out, mean)

temp1 <- ddply(out2, ~avg_sellers.sellers, summarise, mean=mean(avg_markets.marketplaces), sd=sd(avg_markets.marketplaces))


ggscatter(temp1, x = "avg_sellers.sellers", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "kendall",
          xlab = "top 20% sellers per month", ylab = "average active marketplaces per month")


temp2 <- ddply(out2, ~avg_sellers.sellers, summarise, mean=mean(avg_sales.sales), sd=sd(avg_sales.sales))

ggscatter(temp2, x = "avg_sellers.sellers", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "kendall",
          xlab = "top 20% sellers per month", ylab = "average sales per month")

temp3 <- ddply(out2, ~avg_sellers.sellers, summarise, mean=mean(avg_countries.countries), sd=sd(avg_countries.countries))
ggscatter(temp3, x = "avg_sellers.sellers", y = "mean",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "kendall",
          xlab = "top 20% sellers per month", ylab = "average shipping from countries per month")

